### ISSUE TITLE
Acabar el ejercicio

### ISSUE THREAD

**Issue by nasivuela** [Adalab/dorcas-s3-evaluacion-intermedia-mariviru#1]
Te dejo algunas pistas para que puedas acabarlo.

- Quitar etiquetas de HTML extras y estructurar mejor que HTML pinta cada componente. Cuando haces un map, todo lo que retorna cada callback se pinta una vez por cada item de array. Si inspeccionas tu código verás que se te ha ido la mano con los `main`, `h1` y ul.
- Añadir carpeta components para que todo esté más organizadito.
- Mejorar la indentación.
- Añadir keys en los listados (https://reactjs.org/docs/lists-and-keys.html)
- Animarte a hacer destructuring para no escribir tantas veces `this.props`
- Instalar la librería `prop-types` y usarla para comprobar el tipado js de las props.
- Acabar el css
- Eliminar archivos que no usamos (App.test.js, logo.svg...)

También te recomiendo publicar en Github Pages para practicar ;)

A por ello!

**Comment by mariviru** [comment]
Creo que está todo , lo que pasa es que he intentado actualizar la carpeta docs desde la terminal para que se reflejen los cambios en GitHub Pages y no sé si lo he hecho bien o es que tarda en actualizarse la página

**Comment by mariviru** [comment]
Arreglada la carpeta docs, estaba duplicada la carpeta static. Ya se ve en Git Hub Pages

**Comment by nasivuela** [comment]
Buen trabajao @mariviru !! 
Cierro ;)
